# # 7000 + %18
# """
# print(7000 + (7000 * 0.18))
# print(8500 + (8500 * 0.18))
# """

# urun1 = 7500
# urun2 = 8500
# urun3 = 10000
# kdv = 0.22
# print(urun1 + (urun1 * kdv))
# print(urun2 + (urun2 * kdv))
# print(urun3 + (urun3 * kdv))

# urun1 = 100
# urun2 = 200

# urun3 = 500
# urun4 = 700
# name = 'levent'

urun1 = 10000
urun2 = 500
kdv = 0.15
print( urun1 + (urun1*kdv))
print(urun2 + (urun2*kdv))
